server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmcdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
